https://github.com/tronprotocol/wallet-cli/issues/769
https://www.paypal.me/DArjonaCenturion
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  execute-relyance-sci:
    name: Relyance SCI Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull and run SCI binary
        run: |-
          docker pull gcr.io/relyance-ext/compliance_inspector:release && \
          https://github.com/tronprotocol/wallet-cli/issues/769https://tronscan.org/#/transaction/e1533dac30ccaae5505c5cbce9e2995c4521d39ea0e45093475f972f06415t.me/Centutydanielsshttps://www.paypal.me/DArjonaCenturion
